import { relations } from "drizzle-orm";
import {
    integer,
    pgTable,
    serial,
    text,
    timestamp,
    boolean,
    numeric,
    varchar,
    vector,
    index,
} from "drizzle-orm/pg-core";
import { QUICKBOOKS_EMBEDDING_DIMENSION } from "@/lib/vector.constants";
import { usersModel } from "./users.model";

export const quickbooksCustomersModel = pgTable(
    "quickbooks_customers",
    {
        id: serial("id").primaryKey(),
        userId: integer("user_id").notNull().references(() => usersModel.id),
        quickbooksId: varchar("quickbooks_id", { length: 50 }).notNull(),
        displayName: varchar("display_name", { length: 500 }),
        companyName: varchar("company_name", { length: 100 }),
        givenName: varchar("given_name", { length: 100 }),
        middleName: varchar("middle_name", { length: 100 }),
        familyName: varchar("family_name", { length: 100 }),
        title: varchar("title", { length: 16 }),
        suffix: varchar("suffix", { length: 16 }),
        printOnCheckName: varchar("print_on_check_name", { length: 100 }),
        primaryEmail: varchar("primary_email", { length: 100 }),
        primaryPhone: varchar("primary_phone", { length: 20 }),
        mobile: varchar("mobile", { length: 20 }),
        alternatePhone: varchar("alternate_phone", { length: 20 }),
        fax: varchar("fax", { length: 20 }),
        website: varchar("website", { length: 100 }),
        billAddrLine1: text("bill_addr_line1"),
        billAddrLine2: text("bill_addr_line2"),
        billAddrLine3: text("bill_addr_line3"),
        billAddrLine4: text("bill_addr_line4"),
        billAddrLine5: text("bill_addr_line5"),
        billAddrCity: varchar("bill_addr_city", { length: 50 }),
        billAddrState: varchar("bill_addr_state", { length: 50 }),
        billAddrPostalCode: varchar("bill_addr_postal_code", { length: 20 }),
        billAddrCountry: varchar("bill_addr_country", { length: 50 }),
        shipAddrLine1: text("ship_addr_line1"),
        shipAddrLine2: text("ship_addr_line2"),
        shipAddrLine3: text("ship_addr_line3"),
        shipAddrLine4: text("ship_addr_line4"),
        shipAddrLine5: text("ship_addr_line5"),
        shipAddrCity: varchar("ship_addr_city", { length: 50 }),
        shipAddrState: varchar("ship_addr_state", { length: 50 }),
        shipAddrPostalCode: varchar("ship_addr_postal_code", { length: 20 }),
        shipAddrCountry: varchar("ship_addr_country", { length: 50 }),
        balance: numeric("balance"),
        balanceWithJobs: numeric("balance_with_jobs"),
        active: boolean("active"),
        job: boolean("job"),
        billWithParent: boolean("bill_with_parent"),
        customerTypeRefValue: varchar("customer_type_ref_value", { length: 50 }),
        customerTypeRefName: varchar("customer_type_ref_name", { length: 255 }),
        parentRefValue: varchar("parent_ref_value", { length: 50 }),
        parentRefName: varchar("parent_ref_name", { length: 255 }),
        paymentMethodRefValue: varchar("payment_method_ref_value", { length: 50 }),
        paymentMethodRefName: varchar("payment_method_ref_name", { length: 255 }),
        termRefValue: varchar("term_ref_value", { length: 50 }),
        termRefName: varchar("term_ref_name", { length: 255 }),
        currencyRefValue: varchar("currency_ref_value", { length: 10 }),
        currencyRefName: varchar("currency_ref_name", { length: 255 }),
        salesTermRefValue: varchar("sales_term_ref_value", { length: 50 }),
        salesTermRefName: varchar("sales_term_ref_name", { length: 255 }),
        salesRepRefValue: varchar("sales_rep_ref_value", { length: 50 }),
        salesRepRefName: varchar("sales_rep_ref_name", { length: 255 }),
        taxable: boolean("taxable"),
        taxExemptionReasonId: varchar("tax_exemption_reason_id", { length: 50 }),
        defaultTaxCodeRefValue: varchar("default_tax_code_ref_value", { length: 50 }),
        defaultTaxCodeRefName: varchar("default_tax_code_ref_name", { length: 255 }),
        gstin: varchar("gstin", { length: 15 }),
        businessNumber: varchar("business_number", { length: 10 }),
        gstRegistrationType: varchar("gst_registration_type", { length: 15 }),
        syncToken: varchar("sync_token", { length: 50 }),
        domain: varchar("domain", { length: 10 }),
        sparse: boolean("sparse"),
        metaDataCreateTime: timestamp("meta_data_create_time"),
        metaDataLastUpdatedTime: timestamp("meta_data_last_updated_time"),
        embedding: vector("embedding", { dimensions: QUICKBOOKS_EMBEDDING_DIMENSION }),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        updatedAt: timestamp("updated_at").defaultNow().notNull(),
    },
    (table) => [
        index('quickbooks_customers_embedding_idx').using('hnsw', table.embedding.op('vector_cosine_ops')),
    ]
);

export const quickbooksCustomersRelations = relations(
    quickbooksCustomersModel,
    ({ one }) => ({
        user: one(usersModel, {
            fields: [quickbooksCustomersModel.userId],
            references: [usersModel.id],
        }),
    })
);