CREATE TABLE "quickbooks_customers" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"quickbooks_id" varchar(50) NOT NULL,
	"display_name" varchar(500),
	"company_name" varchar(100),
	"given_name" varchar(100),
	"middle_name" varchar(100),
	"family_name" varchar(100),
	"title" varchar(16),
	"suffix" varchar(16),
	"print_on_check_name" varchar(100),
	"primary_email" varchar(100),
	"primary_phone" varchar(20),
	"mobile" varchar(20),
	"alternate_phone" varchar(20),
	"fax" varchar(20),
	"website" varchar(100),
	"bill_addr_line1" text,
	"bill_addr_line2" text,
	"bill_addr_line3" text,
	"bill_addr_line4" text,
	"bill_addr_line5" text,
	"bill_addr_city" varchar(50),
	"bill_addr_state" varchar(50),
	"bill_addr_postal_code" varchar(20),
	"bill_addr_country" varchar(50),
	"ship_addr_line1" text,
	"ship_addr_line2" text,
	"ship_addr_line3" text,
	"ship_addr_line4" text,
	"ship_addr_line5" text,
	"ship_addr_city" varchar(50),
	"ship_addr_state" varchar(50),
	"ship_addr_postal_code" varchar(20),
	"ship_addr_country" varchar(50),
	"balance" numeric,
	"balance_with_jobs" numeric,
	"active" boolean,
	"job" boolean,
	"bill_with_parent" boolean,
	"customer_type_ref_value" varchar(50),
	"customer_type_ref_name" varchar(255),
	"parent_ref_value" varchar(50),
	"parent_ref_name" varchar(255),
	"payment_method_ref_value" varchar(50),
	"payment_method_ref_name" varchar(255),
	"term_ref_value" varchar(50),
	"term_ref_name" varchar(255),
	"currency_ref_value" varchar(10),
	"currency_ref_name" varchar(255),
	"sales_term_ref_value" varchar(50),
	"sales_term_ref_name" varchar(255),
	"sales_rep_ref_value" varchar(50),
	"sales_rep_ref_name" varchar(255),
	"taxable" boolean,
	"tax_exemption_reason_id" varchar(50),
	"default_tax_code_ref_value" varchar(50),
	"default_tax_code_ref_name" varchar(255),
	"gstin" varchar(15),
	"business_number" varchar(10),
	"gst_registration_type" varchar(15),
	"sync_token" varchar(50),
	"domain" varchar(10),
	"sparse" boolean,
	"meta_data_create_time" timestamp,
	"meta_data_last_updated_time" timestamp,
	"embedding" vector(1536),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "quickbooks_customers" ADD CONSTRAINT "quickbooks_customers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "quickbooks_customers_embedding_idx" ON "quickbooks_customers" USING hnsw ("embedding" vector_cosine_ops);