ALTER TABLE "quickbooks_customers" DROP COLUMN "middle_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "title";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "suffix";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "print_on_check_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "mobile";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "alternate_phone";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "fax";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "website";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "bill_addr_line2";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "bill_addr_line3";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "bill_addr_line4";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "bill_addr_line5";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_line1";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_line2";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_line3";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_line4";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_line5";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_city";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_state";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_postal_code";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "ship_addr_country";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "balance_with_jobs";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "job";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "bill_with_parent";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "customer_type_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "customer_type_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "parent_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "parent_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "payment_method_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "payment_method_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "term_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "term_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "currency_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "currency_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "sales_term_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "sales_term_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "sales_rep_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "sales_rep_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "taxable";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "tax_exemption_reason_id";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "default_tax_code_ref_value";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "default_tax_code_ref_name";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "gstin";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "business_number";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "gst_registration_type";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "domain";--> statement-breakpoint
ALTER TABLE "quickbooks_customers" DROP COLUMN "sparse";